dvsa/vol-functional-tests

.github/workflows/cd.yaml
=> chore: ability to run workflow with diff branches

src/test/java/org/dvsa/testing/framework/stepdefs/vol/RefundInterim.java
=> chore:increase kickout time

.github/workflows/cd.yaml
Reverts dvsa/vol-functional-tests#668
=> Revert "chore: ability to run workflow with diff branches"

.github/workflows/e2etest.yaml
=> chore:add role duration

.github/workflows/e2etest.yaml
=> chore:fail on errors set to true 

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/LicenceCreation.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManageApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java
=> chore:Hotfix/sync void

.github/workflows/e2etest.yaml
=> chore:test input optional

.github/workflows/e2etest.yaml
=> chore:refactor var/secrets

.github/workflows/e2etest.yaml
=> chore:workflow dispatch

.snyk
=> chore:snyk ignore

.github/workflows/e2etest.yaml
=> chore:add job def workflow call

.github/workflows/e2etest.yaml
=> chore:add job def workflow dispatch

.github/workflows/e2etest.yaml
Reverts dvsa/vol-functional-tests#687
=> Revert "chore:add job def workflow dispatch"

.github/workflows/e2etest.yaml
=> chore:formatting

.github/workflows/e2etestManual.yaml
=> chore:add manual trigger workflow

.github/workflows/e2eManualTrigger.yaml
=> chore: add back in old workflow

pom.xml
=> chore:increase memory

src/test/java/org/dvsa/testing/framework/Journeys/licence/TypeOfLicenceJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PaymentProcessing.java
=> chore: asset fixes for ECS smoke

src/test/java/org/dvsa/testing/framework/stepdefs/vol/PaymentProcessing.java
=> feat: asset fixes

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/ecmtInternationalRemoval/SubmissionPageSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/BatchProcess.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/FinancialEvidence.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/GoodVarIncreaseVehicle.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/GoodVarUpgrade.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PsvSurrenders.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/SurrenderLogic.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/Surrenders.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/VerifySwitchedOff.java
=> feat: asset asserts

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java
=> chore: assert fix

.github/workflows/e2eManualTrigger.yaml
=> feat: extend duration

src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicHolidays.java
=> chore: sync method

.github/workflows/e2eManualTrigger.yaml
Reverts dvsa/vol-functional-tests#706
=> Revert "feat: extend duration"

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java
=> chore: fix assert

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalApplication.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManagePrinters.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TaskAllocationRules.java, src/test/resources/org/dvsa/testing/framework/features/Internal/Surrender/Sign-In/int-surrender-logic.feature
=> chore: test fixes

src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmissionsJourney.java
=> chore: switch to css selector

src/test/java/org/dvsa/testing/framework/stepdefs/vol/TestRunConfiguration.java
=> feat: alter teardown

src/test/java/org/dvsa/testing/framework/Journeys/licence/ContinuationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/TypeOfLicenceJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/BatchProcess.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ValidLicenceChanges.java, src/test/resources/org/dvsa/testing/framework/features/Internal/Surrender/Sign-In/int-surrender-logic.feature
=> feat:Hotfix/fix internal tests

src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalApplication.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TypeOfLicence.java
=> chore: test fix

pom.xml, src/test/java/org/dvsa/testing/framework/parallel/CustomRunner.java
=> feat: reduce concurrency

CHANGELOG.md, pom.xml, src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmissionsJourney.java
=> chore: added to a submission test 

.github/workflows/e2eManual.yaml
=> chore: yaml

.github/workflows/e2eManual.yaml
=> chore: env var

.github/workflows/e2eManual.yaml
=> chore: remove env var

.github/workflows/e2etest.yaml
=> chore: refactor

.github/workflows/e2etest.yaml
=> chore: call not dispatch

.github/workflows/e2etest.yaml
=> chore: adding back inputs

.github/workflows/e2etest.yaml
=> chore: region

.github/workflows/e2eManual.yaml
=> chore: add permissions

.github/workflows/e2eManual.yaml, .github/workflows/e2etest.yaml
=> chore: revert

.github/workflows/e2etest.yaml
=> chore: role

.github/workflows/e2etest.yaml
=> chore: input

.github/workflows/e2eManual.yaml, .github/workflows/e2etest.yaml
=> chore: inputs

.github/workflows/e2eManual.yaml
=> chore: excluded tags

.github/workflows/e2eManual.yaml
=> chore : typo

.github/workflows/e2eManual.yaml
=> chore: typo

.github/workflows/e2eManual.yaml
=> chore: required

.github/workflows/e2eManual.yaml
=> chore: tags

.github/workflows/e2etest.yaml
=> chore: build id

.github/workflows/e2etest.yaml, src/test/java/org/dvsa/testing/framework/Journeys/licence/BusRegistrationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/BusinessDetailsJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/DirectorJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmitApplicationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ElectronicBusRegistration.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/SubmitSelfServeApplication.java
=> chore: test axe report generation

.github/workflows/e2etest.yaml
=> chore: using maven

.github/workflows/e2etest.yaml
=> chore: temp remove axe

.github/workflows/docker.yaml, run.sh
=> feat: cache 

run.sh
=> chore: syntax

.github/workflows/cd.yaml, .github/workflows/ci.yaml, .github/workflows/maven.yaml, pom.xml
=> chore: ci/cd alterations 

.github/workflows/ci.yaml, .github/workflows/docker.yaml
=> feat: working dir 

.github/workflows/ci.yaml, .github/workflows/docker.yaml, .github/workflows/maven.yaml
=> feat: revert test jar 

README.md
=> feat: change readme

pom.xml
=> chore: pom

.github/workflows/ci.yaml
=> chore: getpush

.github/workflows/e2eFullRegression.yaml
=> fix: typo in parent workflow name

.github/workflows/e2etest.yaml
=> chore: added test input - needed by oidc

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
=> chore:sync

.github/workflows/e2eSmoke.yaml
=> chore:remove default

.github/workflows/e2etest.yaml
=> chore: test input

.github/workflows/e2etest.yaml
=> chore: allignment

.github/workflows/e2etest.yaml
=> chore: temp comment out duration

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSmoke.yaml
=> chore: excluded

.github/workflows/e2etest.yaml
=> chore: duration back in

.github/workflows/e2etest.yaml
=> chore: duration

.github/workflows/e2etest.yaml
Reverts dvsa/vol-functional-tests#829
=> Revert "chore: duration"

src/test/java/org/dvsa/testing/framework/Journeys/licence/APIJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManageApplications.java
=> chore: write lock

src/test/java/org/dvsa/testing/framework/Global/Configuration.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java
=> chore: asset fix

src/test/java/org/dvsa/testing/framework/Global/Configuration.java
=> chore: comment out

src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmissionsJourney.java
=> chore: fix dropdown

src/test/java/org/dvsa/testing/framework/Journeys/licence/OperatingCentreJourney.java
=> Operating centre update fix

src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java, src/test/resources/org/dvsa/testing/framework/EBSR/EBSR.xml
=> chore: assert

pom.xml, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java, src/test/resources/org/dvsa/testing/framework/EBSR/EBSR.xml
=> fix: EBSR test

.github/workflows/maven.yaml
=> chore: correct order

.github/workflows/e2etest.yaml
- [ x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ x] Have you performed a self-review of the code
=> chore: alter duration

src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java
=> chore: reduce kickout

.github/workflows/e2etest.yaml
Reverts dvsa/vol-functional-tests#844
=> Revert "chore: alter duration"

src/test/java/org/dvsa/testing/framework/Journeys/licence/APIJourney.java
=> chore: writelock

.github/workflows/e2etest.yaml
Reverts dvsa/vol-functional-tests#846
=> Revert "Revert "chore: alter duration""

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eManual.yaml, .github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
=> chore: Chore/remove test input

.github/workflows/e2eManual.yaml
=> chore: remove test input

src/test/java/org/dvsa/testing/framework/Journeys/licence/ConvictionsAndPenaltiesJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java
=> chore: add wait

pom.xml
=> chore: bump up

.github/workflows/cd.yaml
=> chore: build maven

.github/workflows/cd.yaml
=> chore: linting 

.github/workflows/cd.yaml
=> chore: linting

.github/workflows/cd.yaml
=> chore: perms

.github/workflows/cd.yaml, .github/workflows/docker.yaml, .github/workflows/maven.yaml, run.sh
=> feat: revert maven/docker workflow changes

infra/docker/batch/Dockerfile
=> feat: revert docker file

pom.xml
=> feature: revert distro management

.github/workflows/maven.yaml
=> chore: bump to 3.2.1

pom.xml
=> feature: increase jvm memory

src/test/java/org/dvsa/testing/framework/Journeys/licence/APIJourney.java
=> feat: thread safety

.github/workflows/ci.yaml
update ci to use renamed action in dvsa/.github repo
=> refactor: reference action moved to dvsa github repo

.github/workflows/e2etest.yaml
=> chore: env

src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java
=> fix:extend EBSR Docs waiting time

.github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
=> chore: tag change

.github/workflows/e2etest.yaml
=> chore: temp disable failure

src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmitApplicationJourney.java
=> fix:new app finance doc option

.github/workflows/e2etest.yaml
revert until permissions are given to terminate batch
=> Revert "chore: cancel aws batch upon workflow cancellation"

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java
=> fix:interim app finance option

src/test/resources/org/dvsa/testing/framework/features/SelfServe/Checker-page/checker-page.feature
=> chore: moved checker step to background

pom.xml, src/test/java/org/dvsa/testing/framework/parallel/CustomRunner.java
=> fix:increase threads

src/test/java/org/dvsa/testing/framework/stepdefs/vol/TypeOfLicence.java
=> chore: trim whitespace assertion

src/test/java/org/dvsa/testing/framework/Journeys/licence/FeeAndPaymentJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java
=> chore: added wait

.github/workflows/e2etest.yaml
=> chore: cancel job

.github/workflows/e2etest.yaml
=> chore: fix false positive

.github/workflows/e2etest.yaml
Reverts dvsa/vol-functional-tests#917
=> Revert "chore: cancel job"

.github/workflows/e2etest.yaml
=> chore: fail on test

.github/workflows/e2etest.yaml
=> chore: cancel batch

.github/workflows/e2etest.yaml
=> chore: submitted status

.github/workflows/e2etest.yaml
=> chore: original job

.github/workflows/e2etest.yaml
=> chore: failures

src/test/java/org/dvsa/testing/framework/Journeys/licence/MessagingJourney.java
=> chore: message scenarios fix as part of assets

.github/workflows/docker.yaml
Amend OIDC role input
Related issue: N/a
=> fix:oidc input var

src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/int-external-search.feature
=> fix: added PP smoke

.github/workflows/e2eSmoke.yaml
=> chore: alter smoke workflow

.github/workflows/docker.yaml, .github/workflows/e2etest.yaml
=> refactor: use org var for aws region

pom.xml
=> chore: up active support

.github/workflows/e2eManual.yaml
=> chore: change env input

.github/workflows/docker.yaml, .github/workflows/e2etest.yaml
=> chore: change from env to vars

.github/workflows/e2etest.yaml
=> chore: bucket name

.github/workflows/e2eManual.yaml, .github/workflows/e2etest.yaml
=> chore: platform_env

.github/workflows/e2etest.yaml
=> chore: oidc

.github/workflows/e2etest.yaml
=> chore: vars

.github/workflows/e2etest.yaml
=> chore: folder name

.github/workflows/e2eSmoke.yaml
=> chore: smoke workflow

.github/workflows/e2etest.yaml
=> refactor: var/env variable work

.github/workflows/e2etest.yaml
- [x ] Have you performed a self-review of the code
=> chore: count

.github/workflows/e2etest.yaml
=> chore: remove environment

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eManual.yaml, .github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
Add input params to e2etest and wrappers to allow external calls
=> refactor: parameterise elements to support calling from v0l-app

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eManual.yaml, .github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
Accept params for job queue details
=> refactor: use input params for job queue

pom.xml
=> fix: bump up dependencies

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSmoke.yaml, pom.xml, src/test/resources/org/dvsa/testing/framework/features/SelfServe/EBSR/non-prod/ebsr.feature
=> chore: use a more stable browser version

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
=> chore: add timeouts for the smoke/full-reg workflows

.github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
=> chore: formatting

src/test/java/org/dvsa/testing/framework/stepdefs/vol/BetaBannerCheck.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PageChecks.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Checker-page/checker-page.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/int-external-search.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/pp-smoke.feature
=> chore: pp smoke test

pom.xml
=> feat: bump up uri

.github/workflows/e2etest.yaml
=> chore: enable failures

src/test/java/org/dvsa/testing/framework/stepdefs/vol/ExternalSearch.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/external-search.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/int-external-search.feature
=> fix: more robust assertion

README.md, pom.xml, src/test/java/org/dvsa/testing/framework/Global/Configuration.java, src/test/java/org/dvsa/testing/framework/Global/GlobalMethods.java
1. Modifying configuration file to now use the Mailpit class within active support
2. Using the latest version of active support 
-->
=> feat: pull emails from mailpit

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java
=> chore: remove payment step

pom.xml, src/test/java/org/dvsa/testing/framework/parallel/CustomRunner.java
=> chore: remove submodule 

pom.xml
=> fix: latest active support

pom.xml
=> feat: consume new as

pom.xml
=> feat: reduce jvm mem

src/test/java/org/dvsa/testing/framework/stepdefs/permits/ecmtInternationalRemoval/SubmissionPageSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalApplication.java
=> fix: smoke test fixes

pom.xml, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TestRunConfiguration.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/EBSR/non-prod/ebsr.feature
=> fix: test opt

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSmoke.yaml
=> chore: use latest browser version in subsequent workflows

pom.xml
=> fix: use new as

pom.xml
=> chore: bump to 3.11.2

.github/workflows/e2eInternalRegression.yaml, .github/workflows/e2eSelfServeRegression.yaml
=> fix: erroneous dash where param is underscored

.github/workflows/e2etest.yaml
=> chore: namespace allure asset name

.github/workflows/e2eSmoke.yaml, .github/workflows/e2etest.yaml
Currently the batch processes are timing out in the workflows i have updated the timeout value to accommodate this.
=> fix: increasing timeout values

src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java
=> feat: add scroll to bottom on ebsr

src/test/resources/org/dvsa/testing/framework/features/SelfServe/Accessibility/create-application-dashboard-accessibility.feature
=> fix: remove tag

.github/workflows/e2etest.yaml
=> chore:needs-

.github/workflows/e2eFullRegression.yaml, .github/workflows/e2eSelfServeRegression.yaml, .github/workflows/e2etest.yaml, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TestRunConfiguration.java
=> fix: time out

.github/workflows/e2eInternalRegression.yaml
Remove param erroring vol-app cd
=> fix: remove erroring param

.github/workflows/e2etest.yaml
=> chore: add bucket vars to overrides

run.sh
* Added resultsBuildNumber to env variables
=> refactor:added results build number to env variables

.github/workflows/e2etest.yaml
=> chore: fail on errors

.github/workflows/e2etest.yaml, src/test/java/org/dvsa/testing/framework/parallel/RunCucumberTests.java
* Added a new xml report to cucumber runner
=> refactor:added new summary report to cucumber runner

src/test/java/org/dvsa/testing/framework/Journeys/licence/APIJourney.java
=> chore: reinstate writelocks into api journey

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/objects/FinancialStandingRate.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateAdminUser.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/FinancialEvidence.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/FinancialStandingRates.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalApplication.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManageApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/VerifySwitchedOff.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Mixed/licence/operating-centre-variation-fee.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Mixed/variation/financial-standing-rates.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Only/application/new-application-publications.feature
=> fix: lgv test fixes

src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Only/application/new-application-publications.feature
=> chore: remove comment out

src/test/java/org/dvsa/testing/framework/Global/GlobalMethods.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/MessagingJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CheckCorrespondence.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/MessagingInternal.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/MessagingSelfServe.java, src/test/resources/org/dvsa/testing/framework/features/messaging/internal-messaging/int-error-validation.feature, src/test/resources/org/dvsa/testing/framework/features/messaging/internal-messaging/int-message-page.feature, src/test/resources/org/dvsa/testing/framework/features/messaging/self-serve-messaging/ss-error-validation.feature, src/test/resources/org/dvsa/testing/framework/features/messaging/self-serve-messaging/ss-message.feature
=> fix: tweak message feature file

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalNavigation.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalNavigation.java, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-generate-letter.feature
* Created an overload for the `getlicence` method
* Created a test for generating a letter
=> fix:added a test to generate a letter

src/test/java/org/dvsa/testing/framework/Journeys/licence/TransportManagerJourney.java, src/test/java/org/dvsa/testing/framework/Utils/Generic/UniversalActions.java, src/test/java/org/dvsa/testing/framework/pageObjects/Driver/DriverUtils.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ExternalSearch.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TmVerifyDifferentOperator.java, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-external-search.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-pay-a-fee.feature
=> chore: move feature file

src/test/java/org/dvsa/testing/framework/Journeys/licence/AdminJourneys/TaskAllocation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeUIJourney.java, src/test/java/org/dvsa/testing/framework/Utils/Generic/UniversalActions.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/internal/AddEditReassignTasks.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PrepTestsStepDefs.java, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-add-a-case.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-create-application.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-pay-a-fee.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-test-allocation.feature
=> feat: task allocation test

src/test/resources/org/dvsa/testing/framework/features/Internal/Operator/unlicensed-operator.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-pay-a-fee.feature, src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-unlicensed-operator.feature
* Added a test for unlicensed licence
=> fix:unlicensed operator

.github/workflows/e2eInternalRegression.yaml, .snyk, pom.xml, run.sh, src/test/java/org/dvsa/testing/framework/Global/GlobalMethods.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/ecmtInternationalRemoval/DeclarationPageSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManagerUsersPage.java, src/test/resources/org/dvsa/testing/framework/features/Internal/Pay-Fees/admin-processing-pay-fee.feature
=> fix:amended broken permits test on login

.github/workflows/e2etest.yaml
=> chore: add cucumber tag to job name

pom.xml
=> fix:reduce jvm to 4gb

src/test/java/org/dvsa/testing/framework/Journeys/licence/AdminJourneys/TaskAllocationRulesJourney.java
=> fix:task allocation index fix

pom.xml, src/test/java/org/dvsa/testing/framework/Global/Configuration.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/FeeAndPaymentJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/permits/BasePermitJourney.java, src/test/java/org/dvsa/testing/framework/Utils/Generic/GenericUtils.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java, src/test/resources/org/dvsa/testing/framework/EBSR/EBSR.xml, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Mixed/LGV-caseworker-applies-for-licence.feature, src/test/resources/org/dvsa/testing/framework/features/permits/internal/annual-ecmt-apgg-euro5_or_euro6/internal-stock-creation.feature, src/test/resources/org/dvsa/testing/framework/features/permits/self-serve/permit/ecmt-international-removal/submission-page.feature
=> fix:optimised pay card method

pom.xml, src/test/java/org/dvsa/testing/framework/stepdefs/permits/annualecmt/LicencePageSteps.java
=> chore: api calls

.github/workflows/docker.yaml
update plugin arch zip and hash for new runner os arch
=> fix: correct plugin for new runner arch

.github/workflows/e2etest.yaml, README.md, pom.xml, src/test/resources/org/dvsa/testing/framework/features/permits/self-serve/permit/ecmt-international-removal/submission-page.feature
Call new surefire report action with a pass percentage of 95%
Related issue: [VOL-6038](https://dvsa.atlassian.net/browse/VOL-6038)
[VOL-6038]: https://dvsa.atlassian.net/browse/VOL-6038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: call updated surefire report summary with 95% pass percentage thhreshold VOL-6038

src/test/resources/org/dvsa/testing/framework/features/permits/internal/permit.ecmt.removal/internal-ecmt-removal-smoke-test.feature
=> fix:remove ecmt smoke

pom.xml, src/test/java/org/dvsa/testing/framework/Global/GlobalMethods.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/DocumentsJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalNavigation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmitApplicationJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/annualecmt/ConfirmationPageSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/common/CommonSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/internal/SubmitPermitApplicationSteps.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateNewOperatorLicense.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ExternalSearch.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ExternalSearchFilter.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalApplication.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalNavigation.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManageApplications.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PageChecks.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/SiteNavigation.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TypeOfLicence.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/WebDav.java
=> feat: up uri constructor

.github/workflows/docker.yaml, pom.xml
=> fix:comment out signing

src/test/java/org/dvsa/testing/framework/Utils/Generic/GenericUtils.java
- Using java http client instead of apache 
- Cleanup/refactoring of some methods using new java 17 features 
=> chore: refactor utils

.github/workflows/e2etest.yaml, pom.xml
=> fix:increase pipeline timeout

.github/workflows/docker.yaml
add necessary perms for workflow dispatch
=> fix: perms needed for despatch to work

.github/workflows/e2eSmoke.yaml, src/test/resources/org/dvsa/testing/framework/features/Internal/Docman/generate-letter.feature, src/test/resources/org/dvsa/testing/framework/features/Internal/Operator/unlicensed-operator.feature, src/test/resources/org/dvsa/testing/framework/features/Internal/Pay-Fees/admin-processing-pay-fee.feature, src/test/resources/org/dvsa/testing/framework/features/Internal/Pay-Fees/transaction-fee.feature, src/test/resources/org/dvsa/testing/framework/features/Internal/Search/internal-search.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/CPMS/Payments/ss-pay-for-application.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/DVLA-Data-Integration/add-goods-vehicles.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Mixed/LGV-caseworker-applies-for-licence.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Mixed/variation/vehicle-authorisation-lgv-text-checks.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/LGV Only/application/type-of-licence-checks.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Licence-Application/Gov-sign-in/application-sign-digitally.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Search/partner-user-external-search.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Surrender-Application/Sign-In/sign-surrender.feature, src/test/resources/org/dvsa/testing/framework/features/permits/internal/annual-ecmt-apgg-euro5_or_euro6/internal-stock-creation.feature
=> chore: back to @smoke

.github/workflows/docker.yaml
=> chore: write

src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/pageObjects/internal/irhp/IrhpPermitsApplyPage.java
=> chore: increase polling time

pom.xml
=> feat: use updated uri constructor

.github/workflows/docker.yaml
use env vars for proxy and port not literals
=> feat: use env vars for proxy and host rather than embedding in xml

.github/workflows/docker.yaml
fix issue with proxy port in batch
=> fix: proxy port not int error in logs

.github/workflows/e2etest.yaml
=> fix: reduce duration

pom.xml
=> fix: use new uri

pom.xml
=> fix: update uri-cons

.github/workflows/e2eInternalRegression.yaml
=> fix: use edge

pom.xml
=> fix: bump active support version

pom.xml
=> fix: api calls 

README.md, pom.xml
=> fix: bump up

pom.xml
=> fix: update pom.xml for new active support

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalNavigation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java
=> feat: prepEnv

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java
=> fix: test fixes

src/test/java/org/dvsa/testing/framework/Journeys/licence/BusRegistrationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/permits/EcmtInternationalRemovalJourney.java, src/test/resources/org/dvsa/testing/framework/features/Internal/Bus-Registration/manual-bus-reg.feature
=> fix : bus reg complete date

src/test/resources/org/dvsa/testing/framework/features/prep-testing/pp-task-allocation.feature
=> fix: remove test

src/test/java/org/dvsa/testing/framework/stepdefs/vol/PrepTestsStepDefs.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/UnlicensedOperatorSteps.java
=> fix: remove submodule, added waits for prep tests

.github/workflows/e2etest.yaml
=> fix: report upload

src/test/java/org/dvsa/testing/framework/stepdefs/vol/InterimLicence.java
=> fix:confirm

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java, src/test/java/org/dvsa/testing/framework/Utils/Generic/UniversalActions.java
=>  fix: new gov sign in step

src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java
=> feat: timeout

src/test/java/org/dvsa/testing/framework/Journeys/licence/SurrenderJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java
=> fix: tick checkbox

.github/workflows/e2etest.yaml, src/test/java/org/dvsa/testing/framework/Journeys/licence/AdminJourneys/TaskAllocation.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/internal/AddEditReassignTasks.java
=> fix: stale element fix, edit user using search

.github/workflows/e2etest.yaml, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ValidLicenceChanges.java
=> fix: remove company changes from test

.github/workflows/e2etest.yaml
=> fix: bring down pass perc temporarily

src/test/java/org/dvsa/testing/framework/Journeys/licence/OperatingCentreJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ValidLicenceChanges.java
=> fix: refresh

src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java
=> fix: retry DOM

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java
=> fix: You have already proved your identity

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java
=> fix: else if

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java
=> fix: sign in

pom.xml
=> fix: active support

pom.xml
=> fix: up active support

pom.xml
=> fix: use 2.7.17

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java
=> fix: revert sign in

.snyk, pom.xml
=> fix: 2.7.20

pom.xml
=> fix: lang 3 bump

pom.xml
=> fix: 2.7.26

src/test/java/org/dvsa/testing/framework/Journeys/licence/InternalNavigation.java
=> feat: int prod user

pom.xml
=> fix: 2.7.27

pom.xml, src/test/java/org/dvsa/testing/framework/Journeys/licence/APIJourney.java
=> fix: remove vehicle declartion

.github/workflows/e2eSelfServeRegression.yaml
=> fix: change tag

.github/workflows/e2etest.yaml
=> fix: seperate step

.github/workflows/e2etest.yaml
=> fix: dl step

src/test/java/org/dvsa/testing/framework/Journeys/licence/PSVJourney.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Accessibility/submissions-accessibility-journey.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/CPMS/Payments/ss-pay-for-application.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/EBSR/non-prod/ebsr.feature
=> fix: temp remove tests

src/test/java/org/dvsa/testing/framework/Journeys/licence/AdminJourneys/TaskAllocation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/ContinuationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/DirectorJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeUIJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SubmissionsJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/TransportManagerJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/InternalSearch.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ManageVehicle.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PsvSurrenders.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ResettingPassword.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/TMDetails.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/ValidLicenceChanges.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/TM-Application/Sign-In/check-tm-details.feature
=> fix:wait and enter text

src/test/resources/org/dvsa/testing/framework/features/Internal/TM-Application/last-tm-letter.feature, src/test/resources/org/dvsa/testing/framework/features/batch-jobs/batch-process.feature
=> fix: remove batch tests

pom.xml, src/test/java/org/dvsa/testing/framework/Journeys/licence/FeeAndPaymentJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/MessagingJourney.java
=> fix: add api new version and test fix

src/test/java/org/dvsa/testing/framework/stepdefs/vol/CreateApplications.java, src/test/resources/org/dvsa/testing/framework/features/SelfServe/CPMS/Payments/ss-pay-for-application.feature
=> fix: pay app test fix

src/test/resources/org/dvsa/testing/framework/features/SelfServe/Accessibility/manage-users-accessibility.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/CPMS/Payments/ss-pay-for-application.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/CPMS/Refunds/refund-interim-fee.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Checker-page/checker-page.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Surrender-Application/Print and Sign/surrender-resume-app.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Update-Licence/after-licence-changes-not-variations.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/User-Account/forgotten-username.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/User-Account/resetting-password.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Variations/goods-variation-increase-vehicle-count-for-oc.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Variations/goods-variation-upgrade.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/Vehicles/vehicle-changes.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/check-correspondence.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/cookies/cookies.feature, src/test/resources/org/dvsa/testing/framework/features/SelfServe/remove-withdrawn-application-ability.feature
=> fix: remove tests

.github/workflows/e2etest.yaml, pom.xml, src/test/java/org/dvsa/testing/framework/Journeys/licence/DirectorJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/DirectorVariation.java
=> fix : remove retry

src/test/java/org/dvsa/testing/framework/Journeys/licence/PSVJourney.java
=> fix: amend tests to assert on validation errors

src/test/java/org/dvsa/testing/framework/Journeys/licence/ContinuationJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/OperatingCentreJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeNavigation.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/Continuations.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/PublicationsRelatedSteps.java
=> fix: waitandClick

src/test/java/org/dvsa/testing/framework/Journeys/licence/GovSignInJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/OperatingCentreJourney.java, src/test/java/org/dvsa/testing/framework/Journeys/licence/SelfServeUIJourney.java, src/test/java/org/dvsa/testing/framework/pageObjects/BasePage.java, src/test/java/org/dvsa/testing/framework/stepdefs/permits/ecmtInternationalRemoval/SubmissionPageSteps.java
=> fix: waitforurl

src/test/java/org/dvsa/testing/framework/Journeys/licence/ContinuationJourney.java, src/test/java/org/dvsa/testing/framework/stepdefs/vol/EBSRUpload.java
=> fix:click by xpath

.github/workflows/e2eAwsBatchJobsSmoke.yaml, pom.xml, src/test/java/org/dvsa/testing/framework/stepdefs/vol/BatchProcess.java, src/test/resources/org/dvsa/testing/framework/features/batch-jobs/batch-concurrent.feature, src/test/resources/org/dvsa/testing/framework/features/batch-jobs/batch-jobs.feature
=> feat: automated batch job testing
